services:
    stsbl.course_group_management.admin.promotion_requests:
        class: Stsbl\CourseGroupManagementBundle\Admin\PromotionRequestAdmin
        arguments: ['Stsbl\CourseGroupManagementBundle\Entity\PromotionRequest']
        calls:
            - [ setLogger, ["@iserv.logger"]]
            - [ setConfig, ["@iserv.config"]]
            - [ setMailer, ["@mailer.local"]]
        tags:
            - { name: iserv.crud }

    stsbl.course_group_management.menu:
        class: Stsbl\CourseGroupManagementBundle\EventListener\MenuSubscriber # Out MenuSubscriber Class
        tags:
            - { name: kernel.event_subscriber } # Tells IServ about our subsriber

    stsbl.course_group_management.dashboard:
        class: Stsbl\CourseGroupManagementBundle\EventListener\DashboardListener # Out DashboardListener Class
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
          - { name: kernel.event_listener, event: iserv.manage.dashboard, method: onBuildManageDashboard}
          - { name: kernel.event_listener, event: iserv_portal.build_idesk, method: onBuildIDesk }

    stsbl.course_group_management.actcoursepromotion:
        class: Stsbl\CourseGroupManagementBundle\Service\ActCoursePromotion
        arguments: ["@iserv.security_handler", "@iserv.shell"]