services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: false

    Stsbl\CourseGroupManagementBundle\:
        resource: '../../*'
        exclude: '../../{Entity,Model,Resources,Tests}/*'

    Stsbl\CourseGroupManagementBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags: ['controller.service_arguments']
        bind:
            $managementMenu: '@iserv.menu.management'
